### PR TITLE
Add a note to the user guide in the README about adding a custom footer to the header

### PR DESCRIPTION
**Pull request by adrn**
I wanted to add some custom text to the bottom of the Astropy header for tests run in a package I maintain that uses the package template. It took me some digging to figure out how to do this, so I thought it might make sense to document it somewhere?

### CODE REVIEW

**Comment by adrn** [comment]
PS: This seems to be working for me locally, running `pytest` directly...but interested to hear if this is actually the right thing to do!

**Review by pllim — APPROVED** [review]
Ooo, nice tip. I like!

Ugh, that Windows failure again. Unrelated.

**Comment by pllim** [comment]
And... I am gonna use this. Thanks again for this PR!!!

**Comment by pllim** [comment]
Question though... where did `hdr` come from?

**Comment by pllim** [comment]
Okay, I think it should have been `footer` based on 

https://github.com/adrn/gala/blob/93ded8a7d79ba0e01cf9e610890d9e38a820a23a/gala/conftest.py#L30-L38

Will fix.

**Comment by adrn** [comment]
Oops, good catch- yes!

**Pull request merged**
