### PR TITLE
Remove astropy from tests requirements

### LINKED ISSUE #49: Astropy shouldn't be listed as a requirement for tests:
`astropy` is listed as a requirement for tests:

```cfg
[options.extras_require]
test =
    numpy
    astropy>=4.0
```

However I don't think it is need, because `astropy` isn't imported in `tests/test-display.py`. Besides, it creates a circular dependency, because tests in `astropy` themselves require `pytest-astropy-header`.

### PR DESCRIPTION
**Pull request by smaret**
Fixes #49.

### CODE REVIEW

**Comment by astrofrog** [comment]
I wonder if we could remove numpy too? Anyone know why it is there?

**Comment by smaret** [comment]
Numpy in imported in the test script:

https://github.com/astropy/pytest-astropy-header/blob/054828893acc3cd535c6fc2b73af715c8d989661/tests/test_display.py#L2-L4

although it looks like it uses `numpy.__version__` only.

**Comment by bsipocz** [comment]
> I wonder if we could remove numpy too? Anyone know why it is there?

I think for the tests we just wanted to have a few importable libraries to display their versions, I'm not sure wht it wasn't handled on the CI config level.

👍  for removing it, too.

**Review by bsipocz — APPROVED** [review]
Thanks! I'm not sure why we never merged this.

**Pull request merged**
