### PR TITLE
Enable Travis notifications to slack

### PR DESCRIPTION
**Pull request by saimn**

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Thanks!

**Comment by pllim** [comment]
Ops, I can't merge. Maybe @astrofrog can.

**Comment by astrofrog** [comment]
Huh weird need to check the permissions

**Comment by astrofrog** [comment]
@pllim - can you try now?

**Comment by pllim** [comment]
@astrofrog , can't see the merge button. Just "Comment".

**Comment by astrofrog** [comment]
Hmm weird, will investigate!

**Comment by astrofrog** [comment]
@pllim - how about now?

**Comment by pllim** [comment]
Yup. Thanks!

**Pull request merged**
