### PR TITLE
Clarify astropy version in test dependency

### LINKED ISSUE #12: Tests fail with older astropy: astropy-helpers not in output
Trying to [package on OpenSUSE](https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:pytest/python-pytest-astropy-header), including Leap 15.2, which has some older versions.

From the [build log](https://build.opensuse.org/package/live_build_log/home:bnavigator:branches:devel:languages:python:pytest/python-pytest-astropy-header/openSUSE_Leap_15.2/x86_64):

```
[   56s] ============================= test session starts ==============================
[   56s] platform linux -- Python 3.6.9, pytest-5.2.4, py-1.8.0, pluggy-0.13.0
[   56s] 
[   56s] Running tests with Astropy version 2.0.3.
[   56s] Running tests in /tmp/pytest-of-abuild/pytest-0/test_override_package_multiple3.
[   56s] 
[   56s] Date: 2019-12-19T03:38:37
[   56s] 
[   56s] Platform: Linux-5.3.15-lp152.1-default-x86_64-with-glibc2.3.4
[   56s] 
[   56s] Executable: /usr/bin/python3
[   56s] 
[   56s] Full Python Version: 
[   56s] 3.6.9 (default, Sep 04 2019, 13:24:18) [GCC]
[   56s] 
[   56s] encodings: sys: utf-8, locale: ANSI_X3.4-1968, filesystem: ascii
[   56s] byteorder: little
[   56s] float info: dig: 15, mant_dig: 15
[   56s] 
[   56s] Package versions: 
[   56s] numpy: 1.17.4
[   56s] pandas: not available
[   56s] 
[   56s] 
[   56s] rootdir: /tmp/pytest-of-abuild/pytest-0/test_override_package_multiple3
[   56s] plugins: astropy-header-0.1.2, cov-2.5.1
[   56s] collected 0 items
```

All tests fail because they look for a line with astropy-helpers, which is not present. I [patched](https://build.opensuse.org/package/view_file/home:bnavigator:branches:devel:languages:python:pytest/python-pytest-astropy-header/debug-test.patch?expand=1) the test script to debug the AssertionError:

```
[   56s]         lines = extract_package_version_lines(out)
[   56s]         try:
[   56s]             assert len(lines) == 6
[   56s]             assert lines[0].startswith('Numpy: ')
[   56s]             assert lines[1].startswith('Scipy: ')
[   56s]             assert lines[2].startswith('Matplotlib: ')
[   56s]             assert lines[3].startswith('h5py: ')
[   56s]             assert lines[4].startswith('scikit-image: ')
[   56s]             assert lines[5].startswith('astropy-helpers: ')
[   56s]             assert 'Running tests with fakepackage version 1.0.2' in out
[   56s]         except AssertionError as e:
[   56s] >           raise Exception(lines)
[   56s] E           Exception: ['Numpy: 1.17.4', 'Scipy: not available', 'Matplotlib: not available', 'h5py: not available', 'scikit-image: not available']
```

Does this mean astropy>=0.3 is required and Leap 15.2 miss out, or can this be fixed?

### PR DESCRIPTION
**Pull request by pllim**
Fix #12 

cc @bnavigator

### CODE REVIEW

**Comment by astrofrog** [comment]
I don't think the issue is the Astropy version - the first Travis job uses astropy 2.x and works fine. I wonder if this will be fixed by #16?

**Comment by pllim** [comment]
In that case, if there is a way @bnavigator can test out the branch at #16 (or from `master` after that PR is merged), that would be great. Otherwise, we will just have to wait until next release for downstream packages to see.

**Comment by pllim** [comment]
@astrofrog , if you really think this is unnecessary, feel free to close the PR without merge.

**Comment by bnavigator** [comment]
[Failure with astropy2.0.3](https://build.opensuse.org/package/live_build_log/home:bnavigator:branches:devel:languages:python:pytest/python-pytest-astropy-header:test/openSUSE_Leap_15.2/x86_64)
```
[   43s] ============================= test session starts ==============================
[   43s] platform linux -- Python 3.6.9, pytest-5.3.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
[   43s] cachedir: .pytest_cache
[   43s] rootdir: /home/abuild/rpmbuild/BUILD/pytest-astropy-header-0.1.2
[   43s] plugins: astropy-header-0.1.2
[   44s] collecting ... collected 19 items
[   44s] 
[   44s] tests/test_display.py::test_default PASSED                               [  5%]
[   44s] tests/test_display.py::test_enabled[cli] FAILED                          [ 10%]
[   44s] tests/test_display.py::test_enabled[ini] FAILED                          [ 15%]
[   44s] tests/test_display.py::test_enabled[conftest] FAILED                     [ 21%]
[   44s] tests/test_display.py::test_explicit_disable[ini] PASSED                 [ 26%]
[   44s] tests/test_display.py::test_explicit_disable[conftest] PASSED            [ 31%]
[   44s] tests/test_display.py::test_override_package_single[cli] FAILED          [ 36%]
[   44s] tests/test_display.py::test_override_package_single[ini] FAILED          [ 42%]
[   44s] tests/test_display.py::test_override_package_single[ini_list] FAILED     [ 47%]
[   45s] tests/test_display.py::test_override_package_single[conftest] FAILED     [ 52%]
[   45s] tests/test_display.py::test_override_package_multiple[cli] FAILED        [ 57%]
[   45s] tests/test_display.py::test_override_package_multiple[ini] FAILED        [ 63%]
[   45s] tests/test_display.py::test_override_package_multiple[ini_list] FAILED   [ 68%]
[   45s] tests/test_display.py::test_override_package_multiple[conftest] FAILED   [ 73%]
[   45s] tests/test_display.py::test_nonexistent[cli] FAILED                      [ 78%]
[   45s] tests/test_display.py::test_nonexistent[ini] FAILED                      [ 84%]
[   45s] tests/test_display.py::test_nonexistent[ini_list] FAILED                 [ 89%]
[   45s] tests/test_display.py::test_nonexistent[conftest] FAILED                 [ 94%]
[   45s] tests/test_display.py::test_modify_in_conftest FAILED                    [100%]
[   45s] 
[   45s] =================================== FAILURES ===================================
[   45s] ______________________________ test_enabled[cli] _______________________________
[   45s] 
[   45s] testdir = <Testdir local('/tmp/pytest-of-abuild/pytest-0/test_enabled0')>
[   45s] capsys = <_pytest.capture.CaptureFixture object at 0x7fd90e396c88>
[   45s] method = 'cli'
[   45s] 
[   45s]     @pytest.mark.parametrize('method', ['cli', 'ini', 'conftest'])
[   45s]     def test_enabled(testdir, capsys, method):
[   45s]         if method == 'cli':
[   45s]             testdir.inline_run("--astropy-header")
[   45s]         elif method == 'ini':
[   45s]             testdir.makeini("""
[   45s]                 [pytest]
[   45s]                 astropy_header = yes
[   45s]             """)
[   45s]             testdir.inline_run()
[   45s]         elif method == 'conftest':
[   45s]             testdir.makeconftest("""
[   45s]                 def pytest_configure(config):
[   45s]                     config.option.astropy_header = True
[   45s]             """)
[   45s]         testdir.inline_run()
[   45s]         out, err = capsys.readouterr()
[   45s]         lines = extract_package_version_lines(out)
[   45s] >       assert len(lines) == 6
[   45s] E       assert 5 == 6
[   45s] E         -5
[   45s] E         +6
...
[   46s] /home/abuild/rpmbuild/BUILD/pytest-astropy-header-0.1.2/tests/test_display.py:138: AssertionError
[   46s] ----------------------------- Captured stdout call -----------------------------
[   46s] ============================= test session starts ==============================
[   46s] platform linux -- Python 3.6.9, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
[   46s] 
[   46s] Running tests with Astropy version 2.0.3.
[   46s] Running tests in /tmp/pytest-of-abuild/pytest-0/test_override_package_multiple1.
[   46s] 
[   46s] Date: 2020-01-28T16:58:34
[   46s] 
[   46s] Platform: Linux-5.3.18-lp152.2-default-x86_64-with-glibc2.3.4
[   46s] 
[   46s] Executable: /usr/bin/python3
[   46s] 
[   46s] Full Python Version: 
[   46s] 3.6.9 (default, Sep 04 2019, 13:24:18) [GCC]
[   46s] 
[   46s] encodings: sys: utf-8, locale: ANSI_X3.4-1968, filesystem: ascii
[   46s] byteorder: little
[   46s] float info: dig: 15, mant_dig: 15
[   46s] 
[   46s] Package versions: 
[   46s] numpy: 1.17.4
[   46s] pandas: not available
[   46s] 
[   46s] 
[   46s] rootdir: /tmp/pytest-of-abuild/pytest-0/test_override_package_multiple1, inifile: tox.ini
[   46s] plugins: astropy-header-0.1.2
[   46s] collected 0 items
```
############################################
[Failure with PR16 patched](https://build.opensuse.org/package/live_build_log/home:bnavigator:astropy-header-test1/python-pytest-astropy-header:test/openSUSE_Leap_15.2/x86_64)
```
[   59s] + py.test-3.6 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v
[   61s] ============================= test session starts ==============================
[   61s] platform linux -- Python 3.6.9, pytest-5.3.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
[   61s] cachedir: .pytest_cache
[   61s] rootdir: /home/abuild/rpmbuild/BUILD/pytest-astropy-header-0.1.2
[   61s] plugins: astropy-header-0.1.2
[   61s] collecting ... collected 20 items
[   61s] 
[   61s] tests/test_display.py::test_default PASSED                               [  5%]
[   61s] tests/test_display.py::test_enabled[cli] PASSED                          [ 10%]
[   61s] tests/test_display.py::test_enabled[ini] PASSED                          [ 15%]
[   61s] tests/test_display.py::test_enabled[conftest] PASSED                     [ 20%]
[   61s] tests/test_display.py::test_astropy_helpers FAILED                       [ 25%]
[   61s] tests/test_display.py::test_explicit_disable[ini] PASSED                 [ 30%]
[   61s] tests/test_display.py::test_explicit_disable[conftest] PASSED            [ 35%]
[   62s] tests/test_display.py::test_override_package_single[cli] PASSED          [ 40%]
[   62s] tests/test_display.py::test_override_package_single[ini] PASSED          [ 45%]
[   62s] tests/test_display.py::test_override_package_single[ini_list] PASSED     [ 50%]
[   62s] tests/test_display.py::test_override_package_single[conftest] PASSED     [ 55%]
[   62s] tests/test_display.py::test_override_package_multiple[cli] PASSED        [ 60%]
[   62s] tests/test_display.py::test_override_package_multiple[ini] PASSED        [ 65%]
[   62s] tests/test_display.py::test_override_package_multiple[ini_list] PASSED   [ 70%]
[   62s] tests/test_display.py::test_override_package_multiple[conftest] PASSED   [ 75%]
[   62s] tests/test_display.py::test_nonexistent[cli] PASSED                      [ 80%]
[   63s] tests/test_display.py::test_nonexistent[ini] PASSED                      [ 85%]
[   63s] tests/test_display.py::test_nonexistent[ini_list] PASSED                 [ 90%]
[   63s] tests/test_display.py::test_nonexistent[conftest] PASSED                 [ 95%]
[   63s] tests/test_display.py::test_modify_in_conftest PASSED                    [100%]
[   63s] 
[   63s] =================================== FAILURES ===================================
[   63s] _____________________________ test_astropy_helpers _____________________________
[   63s] 
[   63s] testdir = <Testdir local('/tmp/pytest-of-abuild/pytest-0/test_astropy_helpers0')>
[   63s] capsys = <_pytest.capture.CaptureFixture object at 0x7f6ee9cbecc0>
[   63s] 
[   63s]     def test_astropy_helpers(testdir, capsys):
[   63s]         try:
[   63s]             builtins._ASTROPY_SETUP_ = True
[   63s]             testdir.inline_run("--astropy-header")
[   63s]         finally:
[   63s]             del builtins._ASTROPY_SETUP_
[   63s]         out, err = capsys.readouterr()
[   63s]         lines = extract_package_version_lines(out)
[   63s] >       assert len(lines) == 6
[   63s] E       assert 5 == 6
[   63s] E         -5
[   63s] E         +6
[   63s] 
[   63s] /home/abuild/rpmbuild/BUILD/pytest-astropy-header-0.1.2/tests/test_display.py:72: AssertionError
[   63s] ========================= 1 failed, 19 passed in 2.28s =========================
[   63s] error: Bad exit status from /var/tmp/rpm-tmp.ArWhe3 (%check)
[   63s] 
[   63s] 
[   63s] RPM build errors:
[   63s]     Bad exit status from /var/tmp/rpm-tmp.ArWhe3 (%check)
[   63s] 
[   63s] lamb23 failed "build python-pytest-astropy-header.spec" at Tue Jan 28 16:59:20 UTC 2020.
```

Don't know why the second one is not as verbose

**Comment by bnavigator** [comment]
Still failing on Leap 15.2 as posted above, deleting the test repos now.

**Comment by pllim** [comment]
Sorry that this didn't help. 😞

**Comment by bnavigator** [comment]
@pllim, it's actually #16 that didn't help. This one here would but is obviously not desired.

**Comment by pllim** [comment]
Oh... ops! Well, I can open another PR if this is decided to be good enough. Please let me know. 😬

**Pull request closed without merging**
