### PR TITLE
MNT: Bump stuff in setup.cfg and Travis CI

### LINKED ISSUE #21: Add python_requires to setup.cfg
In https://github.com/astropy/pytest-astropy-header/pull/19, the Python 2.7 testing was dropped. We should explicitly define ``python_requires`` in ``setup.cfg`` to officially make 3.6 the oldest supported version.

cc @pllim

### PR DESCRIPTION
**Pull request by pllim**
Fix #21 

But wait, there's more!

### CODE REVIEW

**Comment by pllim** [comment]
I don't think PYTHON_VERSION reported in Checks summary are correct. If you look at the log, the Python version used is as defined in matrix instead.

Not sure where `test_env.py` came from.

**Comment by astrofrog** [comment]
@pllim - while you're at it, do you want to update the package infrastructure as in https://github.com/astropy/pytest-remotedata/pull/48? I think you can copy the Travis file basically as-is, and the tox file will need only small adjustments. The pyproject.toml file can be copied over as-is too.

**Comment by pllim** [comment]
Sure...

**Comment by pllim** [comment]
I think it is easier if I open a new PR.

**Pull request closed without merging**
