### PR TITLE
Don't show astropy-helpers version in packages that don't use it

### LINKED ISSUE #14: astropy-helpers version is misleading
In a package that uses this plugin and has `astropy` as dependency, `astropy-helpers` is reported in the header and is actually extracted from `astropy`. This confused me because I removed `astropy-helpers` from my package (e.g., spacetelescope/stsynphot_refactor#96) but the test header still reports `astropy-helpers: 4.0.1`.

https://github.com/astropy/pytest-astropy-header/blob/210f926ffe5b093f11aebc03dae3d253a191a280/pytest_astropy_header/display.py#L160-L167

### PR DESCRIPTION
**Pull request by astrofrog**
Fixes https://github.com/astropy/pytest-astropy-header/issues/14

### CODE REVIEW

**Comment by astrofrog** [comment]
@mwcraig @pllim - does this seem ok?

**Comment by mwcraig** [comment]
Yes-won’t have a chance to test out for a couple of days but this seems like it will fix the issue.

**Comment by pllim** [comment]
Let me use this branch and get back to you.

**Review by pllim — APPROVED** [review]
LGTM. Thanks!

```
Running tests with synphot version 0.3.dev21+gdc6d681.
Running tests in synphot docs.

Date: 2020-01-28T15:46:57

Platform: Linux-4.15.0-1066-azure-x86_64-with-debian-stretch-sid

Executable: /opt/hostedtoolcache/Python/3.7.6/x64/bin/python

Full Python Version: 
3.7.6 (default, Jan 10 2020, 10:35:35) 
[GCC 5.4.0 20160609]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.18.1
Scipy: 1.4.1
Matplotlib: not available
Pandas: not available
Astropy: 4.0
scikit-image: not available

Using Astropy options: remote_data: none.
```

**Comment by bnavigator** [comment]
This did not fix #12 (see also #13 )

**Pull request merged**
